name: docker-publish

on:
  push:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest release version
        id: version
        run: echo "::set-output name=VERSION::$(curl -s https://api.github.com/repos/xtekky/gpt4free/releases/latest | jq -r '.tag_name')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gpt4free-arm:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/gpt4free-arm:latest
          platforms: linux/arm64

      - name: Commit and push version.txt changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          echo "VERSION=${{ steps.version.outputs.VERSION }}" > version.txt
          git add version.txt
          git commit -m "Bump version to ${{ steps.version.outputs.VERSION }}"
          git push origin HEAD:${{ github.ref }}
