name: docker-publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    paths:
      - '.github/workflows/docker-publish.yml' # Specify the path to trigger workflow dispatch

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      id: version
      set: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(curl -s https://api.github.com/repos/xtekky/gpt4free/releases/latest | jq -r '.tag_name')"

  build-image:
    runs-on: ubuntu-latest
    needs: get-version
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.get-version.outputs.version != env.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gpt4free-arm:${{ steps.get-version.outputs.version }}
          platforms: linux/arm64

      - name: Extract image digest
        id: digest
        run: echo "::set-output name=digest::$(docker inspect --format='{{index .RepoDigests 0}}' ${{ steps.docker_build.outputs.image }})"
      
      - name: Store image digest
        id: store_digest
        run: echo "DOCKER_IMAGE_DIGEST=${{ steps.digest.outputs.digest }}" >> $GITHUB_ENV
