name: Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily, adjust the schedule as needed
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add upstream https://github.com/xtekky/gpt4free.git  

    - name: Fetch upstream changes
      run: git fetch upstream
  
    - name: Check for changes
      id: check_changes
      run: |
        changes=$(git diff --name-only HEAD...upstream/main | wc -l)
        if [[ $changes -eq 0 ]]; then
          echo "No changes detected in the upstream repository."
          exit 1
        fi
      
    - name: Merge changes (excluding some files)
      if: steps.check_changes.outputs.changes > 0
      run: |
        git merge --no-commit --no-ff upstream/main || echo "Merge failed. Reason: $(git status --short)"
        # Skip the specific file from being committed
        git checkout --theirs -- .github/workflows/*.{yml,yaml} requirements.txt
        git add -u 
      
    - name: Commit changes
      if: steps.check_changes.outputs.changes > 0
      run: git commit -m "Sync upstream changes"

    - name: Push changes to fork
      if: steps.check_changes.outputs.changes > 0
      run: git push origin HEAD
